collections:
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 3.0.2
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.2.0
