collections:
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 4.5.0
  # see https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 1.3.0
